@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Candidato {
  - qntVotos: Integer
  - partidao: Partido
  - eleito: boolean
  - genero: char
  - cargo: int
  - ID: int
  - nasc: LocalDate
  - nomeUrna: String
  + getGenero(): char
  + getCargo(): int
  + setEleito(boolean): void
  + getID(): int
  + setPartidao(Partido): void
  + isEleito(): boolean
  + addQntVotos(Integer): void
  + toString(): String
  + getPartidao(): Partido
  + imprimeListaCand(List<Candidato>): void
  + getNomeUrna(): String
  + getQntVotos(): int
  + getNasc(): LocalDate
  + compareTo(Candidato): int
}
class Federacao {
  - ID: int
  - partidos: ArrayList<Partido>
  + getPartidos(): ArrayList<Partido>
  + setID(int): void
  + inserePartido(Partido): void
  + getID(): int
}
class Partido {
  - votosPartidarios: int
  - numeroUrna: int
  - siglaPartido: String
  - candidatos: ArrayList<Candidato>
  - fed: Federacao
  + imprimeListaPartido(List<Partido>): void
  + InsereCand(Candidato): void
  + setFed(Federacao): void
  + getVotos(): Integer
  + addVotosPartidarios(int): void
  + isInFed(): Boolean
  + toString(): String
  + getVotosPartidarios(): int
  + getSiglaPartido(): String
  + getFed(): Federacao
  + compareTo(Partido): int
  + getCandidatos(): ArrayList<Candidato>
  + getNumeroUrna(): int
  + estatisticasCands(): String
}

Candidato "1" *-[#595959,plain]-> "partidao\n1" Partido   
Federacao "1" *-[#595959,plain]-> "partidos\n*" Partido   
Partido   "1" *-[#595959,plain]-> "candidatos\n*" Candidato 
Partido   "1" *-[#595959,plain]-> "fed\n1" Federacao 
@enduml
